//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elephant.Hank.WindowsApplication.Framework.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int ExecutionTimeLapseInMilli {
            get {
                return ((int)(this["ExecutionTimeLapseInMilli"]));
            }
            set {
                this["ExecutionTimeLapseInMilli"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.140.3.1:26264/")]
        public string BaseApiUrl {
            get {
                return ((string)(this["BaseApiUrl"]));
            }
            set {
                this["BaseApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\GitHub\\selenium-grid\\ProtractorAutomation-V-3.0")]
        public string FrameworkBasePath {
            get {
                return ((string)(this["FrameworkBasePath"]));
            }
            set {
                this["FrameworkBasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9000/")]
        public string BaseWebUrl {
            get {
                return ((string)(this["BaseWebUrl"]));
            }
            set {
                this["BaseWebUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gurpreet.singh@inspopindia.com")]
        public string FaultedEmailId {
            get {
                return ((string)(this["FaultedEmailId"]));
            }
            set {
                this["FaultedEmailId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("168")]
        public int ClearLogHours {
            get {
                return ((int)(this["ClearLogHours"]));
            }
            set {
                this["ClearLogHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int ClearReportHours {
            get {
                return ((int)(this["ClearReportHours"]));
            }
            set {
                this["ClearReportHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int CleanerRunAtHour {
            get {
                return ((int)(this["CleanerRunAtHour"]));
            }
            set {
                this["CleanerRunAtHour"] = value;
            }
        }
    }
}
